language: node_js
node_js:
  - "node" 
branches:
  only:
    - master
script:
  - "yarn run lint"
  - "yarn test"

install:
  - npm install -g firebase-tools

after_success:
  - firebase deploy --token $FIREBASE_TOKEN